apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone
  namespace: capstone
  labels:
    app: capstone
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  selector:
    matchLabels:
      app: capstone
      tier: web
  template:
    metadata:
      labels:
        app: capstone
        tier: web
    spec:
      containers:
      - name: capstone
        image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          periodSeconds: 5