apiVersion: v1
kind: Service
metadata:
  labels:
    app: capstone
  name: capstone
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    {{ if eq .Values.service.type "NodePort" }}
    nodePort: {{ toYaml .Values.service.nodeport }}
    {{ end }}
  selector:
    app: capstone
    tier: web
  type: {{ toYaml .Values.service.type }}